language: ruby
rvm:
  - 1.9.3 # We don't care, but stops travis-lint from complaining
cache:
  apt: true
  directories:
    - $HOME/.pub-cache
before_install:
  - sudo apt-get update --yes
install:
  # Setup the Dart SDK
  - wget http://storage.googleapis.com/dart-archive/channels/stable/release/latest/editor/darteditor-linux-x64.zip
  - unzip -q darteditor-linux-x64.zip -d .temp
  - export DART_SDK="$TRAVIS_BUILD_DIR/.temp/dart/dart-sdk/bin"
  - export PATH="$PATH:$DART_SDK"
  - dart --version

  # Setup Content Shell
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install --yes ttf-indic-fonts ttf-mscorefonts-installer ttf-dejavu-core ttf-kochi-gothic ttf-kochi-mincho ttf-thai-tlwg
  - .temp/dart/chromium/download_contentshell.sh
  - unzip content_shell-linux-x64-release.zip -d .temp
  - mv .temp/drt-lucid64-full-stable* .temp/content_shell
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/.temp/content_shell"

  # Start xvfb for Content Shell
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - pub get
script:
  - dart tool/hop_runner.dart test --content_shell=content_shell -- test/test.html
