name: browser_unittest
version: 0.3.0
author: Dan Schultz <dan@mixbook.com>
description: A set of tools for running and parsing headless unit tests with Content Shell.
homepage: https://github.com/Mixbook/browser_unittest.dart
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  bot_io: '<0.26.0'
  hop: '>=0.27.0 <0.29.0'
  stack_trace: '>=0.9.2'
  unittest: '>=0.9.1'
